### ISSUE TITLE
Diacritics improvements needed

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/alex-brush#7]
Hi @crystaltype, after pulling the latest source file and producing the new font, there are still some diacritics issues. Please inspect the following and the list in the [Font Mastering Issue](https://github.com/googlefonts/alex-brush/issues/1) to address all the improvements needed in the font.

- [ ] The combining marks created have gone way too up of the base glyph, they should be at a hight similar to the original position of the font. Please add the original glyphs to the background as a reference.
- [ ] All the composite glyphs should be produced combining a base glyph + comb mark
- [ ] DIacritics should be aligned
- [ ] Subtly balancing the overall thickness, size and visual weight among marks. E.g., the circumflex seems to be lighter or smaller than acute or grave
- [ ] Balancing the sidebearing/spacing of the marks to prevent them to alter the spacing of the composite glyphs
- [ ] Stacked diacritics distance and position should be balanced
- [ ] Uppercase diacritics `comb.case` are needed for Caps as they differ in size and thickness

**Original diacritics**
![Alex-Brush-misaligned-diacritics](https://user-images.githubusercontent.com/48698976/109740320-17890300-7b99-11eb-93dd-beb42ce32d5c.png)

**Current diacritics**
![Screen Shot 2021-03-02 at 20 13 58](https://user-images.githubusercontent.com/48698976/109740388-325b7780-7b99-11eb-84d6-5c1a6cde0574.png)

**Stacked diacritics before**
![Screen Shot 2021-03-02 at 20 15 21](https://user-images.githubusercontent.com/48698976/109740702-b31a7380-7b99-11eb-8f34-444adaa0d395.png)

**Stacked diacritics after**
![Screen Shot 2021-03-02 at 20 15 47](https://user-images.githubusercontent.com/48698976/109740678-aa29a200-7b99-11eb-9bf6-4f4951637ccd.png)

**Comment by vv-monsalve** [comment]
before
<img width="1232" alt="Screen Shot 2021-03-03 at 21 55 41" src="https://user-images.githubusercontent.com/48698976/109909589-5b046f80-7c74-11eb-960c-26faa1bffff2.png">
after
<img width="1232" alt="Screen Shot 2021-03-03 at 21 54 52" src="https://user-images.githubusercontent.com/48698976/109909584-593aac00-7c74-11eb-821b-7458cf548315.png">
- The overall thickness of the diacritics has improved, however, some of them could look a bit heavy (e.g. circumflex), please include some of the contrast of the original marks to recover a bit of the lightness.

<img width="1234" alt="Screen Shot 2021-03-03 at 23 23 29" src="https://user-images.githubusercontent.com/48698976/109911208-a3715c80-7c77-11eb-8f7a-7b2f6320073e.png">
<img width="1234" alt="Screen Shot 2021-03-03 at 23 24 06" src="https://user-images.githubusercontent.com/48698976/109911215-a5d3b680-7c77-11eb-9dd3-2a1e7603c550.png">


- Case diacritics tend to be slightly different from the lowercase ones. Usually, they are more sloped to avoid being too tall, circumflex or caron has a wider angle, thus they could be a bit wider than lc-marks to compensate the angle and to not look small for their base letters, among others.

**Comment by crystaltype** [comment]
Okay, I tried to improve the contrast and create new case diacritics. I think it's ready to be published.
<img width="1337" alt="Screen Shot 2021-03-17 at 14 50 17" src="https://user-images.githubusercontent.com/20129845/111433035-55a52b80-8730-11eb-89b2-bb3d736500a9.png">
<img width="1366" alt="Screen Shot 2021-03-17 at 14 50 59" src="https://user-images.githubusercontent.com/20129845/111433053-5b9b0c80-8730-11eb-85f1-e8ed15085d2e.png">

**Comment by crystaltype** [comment]
I improved the diacritics per your suggestions. I think Alexbrush is now ready to be published.

<img width="1068" alt="Screen Shot 2021-03-17 at 15 19 43" src="https://user-images.githubusercontent.com/20129845/111436278-6061bf80-8734-11eb-949d-afdac3dacbbe.png">

**Comment by vv-monsalve** [comment]
Hi @crystaltype,

Please inspect caron and macron that seem lighter than the other marks, and circumflexgrave plus circumflexacute look as if they were touching.

I tried to pull the latest files but they are not in the repo, please push them so I can generate new preview and comparative images.

**Comment by crystaltype** [comment]
Hello @vv-monsalve 
<img width="843" alt="Screen Shot 2021-03-18 at 14 32 20" src="https://user-images.githubusercontent.com/20129845/111588948-cf075180-87f6-11eb-81ca-4a5ced549231.png">

I've fixed them. 

> I tried to pull the latest files but they are not in the repo, please push them so I can generate new preview and comparative images.

Hmm I used git push command, do I need to make a pull request too?

**Comment by vv-monsalve** [comment]
> Hmm I used git push command, do I need to make a pull request too?

Probably you pushed to your fork but not to this upstream folder, when looking at the [list of commits](https://github.com/googlefonts/alex-brush/commits/main) the last was mine 17 days ago.

What would be best to keep the process clean is you could keep pushing to your fork but remember to PR to this repository, which is the traditional workflow in any case.
